const mvpList = [
  {"Player Name":"Don Young","Points":6},
  {"Player Name":"Danny Plowman","Points":4},
  {"Player Name":"Jim Bullock","Points":4},
  {"Player Name":"Thomas Who","Points":4},
  {"Player Name":"Jim Nevin","Points":3},
  {"Player Name":"Dan Schroeder","Points":3},
  {"Player Name":"Doug Andrus","Points":3},
  {"Player Name":"Tony Perez","Points":3},
  {"Player Name":"Felipe Ochoa","Points":3},
  {"Player Name":"Don Murphy","Points":3},
  {"Player Name":"Shawn Mcbride","Points":3},
  {"Player Name":"Juergen Jackert","Points":3},
  {"Player Name":"Luis Asavedo","Points":3},
  {"Player Name":"Ignasio Gutierrez","Points":3},
  {"Player Name":"Ruth Drozdek","Points":3},
  {"Player Name":"Mike Uhlean","Points":2},
  {"Player Name":"Roger Gault","Points":2},
  {"Player Name":"Shawn Vitolka","Points":2},
  {"Player Name":"Doc Halek","Points":2},
  {"Player Name":"Jeronimo Ramirez","Points":2}
];