const mvpList = [
  {"Player Name":"Doug Andrus","HC":16},
  {"Player Name":"Kevin Pattenaude","HC":13},
  {"Player Name":"Shawn Mcbride","HC":13},
  {"Player Name":"Doc Halek","HC":12},
  {"Player Name":"Jariel Diaz","HC":12},
  {"Player Name":"Jeremie Ketner","HC":12},
  {"Player Name":"Jim Nevin","HC":12},
  {"Player Name":"Don Rak","HC":10},
  {"Player Name":"Freddy Izguerra","HC":10},
  {"Player Name":"Tom Nevin","HC":10},
  {"Player Name":"Joey Sanchez","HC":8},
  {"Player Name":"Noe Castana","HC":8},
  {"Player Name":"Phil Nelson","HC":8},
  {"Player Name":"Randy Rycraft","HC":8},
  {"Player Name":"Tony Castro","HC":8},
  {"Player Name":"Tony Guthrie","HC":8},
  {"Player Name":"Felipe Ochoa","HC":7},
  {"Player Name":"Jeronimo Ramirez","HC":7},
  {"Player Name":"Jim Czenk","HC":7},
  {"Player Name":"Mario Orenday","HC":7}
];
