const mvpList = [
  {"Player Name":"Shawn Mcbride","Points":24},
  {"Player Name":"Doug Andrus","Points":22},
  {"Player Name":"Don Rak","Points":22},
  {"Player Name":"Jim Nevin","Points":21},
  {"Player Name":"Mike Uhlean","Points":20},
  {"Player Name":"Mario Orenday","Points":20},
  {"Player Name":"Freddy Izguerra","Points":20},
  {"Player Name":"Jariel Diaz","Points":20},
  {"Player Name":"Luke Valenzuela","Points":18},
  {"Player Name":"Kevin Pattenaude","Points":17},
  {"Player Name":"Jeremie Ketner","Points":16},
  {"Player Name":"Doc Halek","Points":14},
  {"Player Name":"Joey Sanchez","Points":14},
  {"Player Name":"Buster Fuller","Points":14},
  {"Player Name":"Doug Misner","Points":14},
  {"Player Name":"Chuck Feager","Points":13},
  {"Player Name":"Noe Castana","Points":13},
  {"Player Name":"Joe Crutchfield","Points":12},
  {"Player Name":"Tom Nevin","Points":12},
  {"Player Name":"Phil Nelson","Points":12}
];